[project]
name = "up-vault"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "senbinil", email = "senbinil@yandex.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
up-vault = "up_vault:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
